name: "SemanticRelease"
description: "Composit GitHub Action that use semantic-release to automates the whole package release"

inputs:
  token:
    description: "GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Semantic Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: GH_TOKEN=${{ inputs.token }} npx semantic-release
