name: "SemanticRelease"
description: "Composit GitHub Action that use semantic-release to automates the whole package release"

inputs:
  token:
    description: "GITHUB_TOKEN"
    required: true
  checkout:
    description: "Flag to indicate whether the repo has already been checked out"
    default: true
  node-version:
    description: "Pick the node version to use [20.x, 22.x]"
    default: 20.x

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.checkout == 'true' }}
      name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Semantic Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: npx semantic-release
