name: SemanticRelease

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  release:
    name: SemanticRelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: npx semantic-release
